config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  # Nested resource routes give us access to replies from each post
  resources :posts do
  	resources :replies
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :replies, dependent: :destroy
  validates :title, :body, presence: true
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :post
  validates :name, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def create
  	@post = Post.new(post_params)

  	if @post.save
  	  redirect_to root_path, notice: "Post successfully created!"
  	else
  	  redirect_to root_path, alert: "Invalid input, post creation failed..."
  	end
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])

  	if @post.update(post_params)
  	  redirect_to @post, notice: "Post successfully updated!"
  	else
      flash.now[:alert] = "Invalid input, post update failed..."
  	  render :edit
  	end
  end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy

  	redirect_to root_path, notice: "Post successfully deleted!"
  end

  private
  	def post_params
  	  params.require(:post).permit(:title, :body)
  	end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@reply = @post.replies.create(replies_params)
    if @reply.valid?
  	  redirect_to post_path(@post), notice: "Reply successfully created!"
    else
      redirect_to post_path(@post), alert: "Invalid input, reply creation failed..."
    end
  end

  def destroy
  	@post = Post.find(params[:post_id])
  	@reply = @post.replies.find(params[:id])
  	@reply.destroy
  	redirect_to post_path(@post), notice: "Reply successfully deleted!"
  end

  private
  	def replies_params
  	  params.require(:reply).permit(:name, :body)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_alerts.html.erb
<%# Styles alert with bootstrap and make it red to signify an error %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_notices.html.erb
<%# Styles notice with bootstrap and make it green to signify success %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Rails-Post-Reply</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Put body in a bootstrap container -->
    <div class="container">
      <!-- If any notices or alerts are sent, render them with corresponding partial -->
      <% if notice %>
        <%= render 'layouts/notices' %>
      <% end %>
      <% if alert %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Bootstrap script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%# Create a form for post that has placeholders %>
<%= form_with model: post do |form| %>
  <div class="form-group mb-3">
  	<%= form.text_field :title, class: "form-control mb-1", placeholder: "Subject" %>
  	<%= form.text_area :body, class: "form-control", placeholder: "Body", rows: "5" %>
  </div>

  <div class="form-group ms-2">
  	<%= form.submit "Submit", class: "btn btn-secondary mb-3" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%# Render the new/edit post form in a card %>
<div class="card w-100 mx-auto mt-5 mb-3 text-dark bg-light">
  <div class="card-header">
  	<p class="card-text text-center fs-4">Edit Post</p>
  </div>
  <div class="card-body">
    <%= render "form", post: @post %>
  </div>
</div>

<%# Add a back button that redirects back to the show view for the post %>
<div class="container mb-5 text-center">
  <%= link_to "Back", @post, class: 'btn btn-dark px-5' %>
</div>

app/views/posts/index.html.erb
<%# Home page title %>
<div class="container w-100 text-center mt-5 mb-5">
  <h1>RoR Bootcamp Message Board</h1>
</div>

<%# Check if there are any posts %>
<% if @posts.empty? %>
  <%# If the posts array is empty, make user aware with a card %>
  <div class="card w-75 mx-auto mb-5">
    <div class="card-header text-center">
      <p class="card-text">No posts...</p>
    </div>
  </div>
<% else %>
  <%# Otherwise, list all posts as clickable links %>
  <div class="list-group mb-5">
    <%# A fully-disabled link; used as a header for the list %>
    <a href="#" class="list-group-item list-group-item-secondary text-center pe-none py-2">
  	  <span class="fs-5">Posts:</span>
    </a>
    <%# Goes thru each post and creates a clickable list-group-item link %>
    <% @posts.each do |post| %>
      <%= link_to post.title, post, class: "list-group-item list-group-item-action list-group-item-light py-3" %>
    <% end %>
  </div>
<% end %>

<%# New post form rendered in a card %>
<div class="card w-100 mx-auto mb-5 text-dark bg-light">
  <div class="card-header">
  	<p class="card-text text-center">New post</p>
  </div>
  <div class="card-body">
    <%# Needs a blank Post instance to create the form, so create it and pass it in %>
    <%= render "form", post: Post.new %>
  </div>
</div>

app/views/posts/show.html.erb
<%# Display the post and give the option to edit and delete it %>
<div class="card w-100 mt-5 mb-5 mx-auto text-dark bg-light">
  <div class="card-header fs-5 fw-bold py-3">
  	<%= @post.title %>
  </div>
  <div class="card-body mb-1">
    <p class="card-text"><%= simple_format(@post.body) %></p>
    <div class="text-center">
	  <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-secondary px-4 mx-1' %>
	  <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger mx-1' %>
	</div>
  </div>
</div>

<%# Check if there are any replies for this post %>
<% if @post.replies.empty? %>
  <%# If the replies array is empty, make user aware with a card %>
  <div class="card w-75 mx-auto">
    <div class="card-header text-center">
      <p class="card-text">No replies...</p>
    </div>
  </div>
<% else %>
  <%# If there are replies, display all the replies %>
  <div class="card w-75 mx-auto text-dark bg-light">
    <div class="card-header text-center">
      <p class="card-text">Replies:</p>
    </div>
  </div>
  <%# Renders each reply one by one using the partial expansion feature %>
  <%# It's like rendering replies/_reply.html.erb with each reply as the param %>
  <%= render @post.replies %>
<% end %>

<%# New reply form rendered in a card %>
<div class="card w-100 mx-auto mt-5 mb-3 text-dark bg-light">
  <div class="card-header">
  	<p class="card-text text-center">New reply</p>
  </div>
  <div class="card-body">
    <%= render "replies/form" %>
  </div>
</div>

<%# Adds a back button at the bottom that takes user back to root page %>
<div class="container mb-5 text-center">
  <%= link_to "Back", root_path, class: 'btn btn-dark px-5' %>
</div>

app/views/replies/_form.html.erb
<%# Create a reply form for a specific post, with placeholders %>
<%= form_with model: [@post, @post.replies.build] do |form| %>
  <div class="form-group h-100 mb-3">
  	<%= form.text_field :name, class: "form-control mb-1", placeholder: "Name" %>
  	<%= form.text_area :body, class: "form-control", placeholder: "Body", rows: "5" %>
  </div>
  <div class="form-group ms-2">
  	<%= form.submit "Submit", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/replies/_reply.html.erb
<%# Display the reply with " says:" appended to name; provide delete button %>
<div class="card mb-2 w-75 mx-auto">
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted"><%= reply.name %> says:</h6>
    <p class="card-text"><%= simple_format(reply.body) %></p>
    <div class="text-center">
      <%= link_to 'Delete', [reply.post, reply], method: :delete, data: { confirm: "Are you sure?" }, class: "btn-sm btn-danger" %>
    </div>
  </div>
</div>